# Write a program to input 8 numbers from the user and display all the unique number (once).
s=set()
num=input("Enter the 1st  number : ")
s.add(int(num))
num=input("Enter the 2nd  number : ")
s.add(int(num))
num=input("Enter the 3rd  number : ")
s.add(int(num))
num=input("Enter the 4th  number : ")
s.add(int(num))
num=input("Enter the 5th  number : ")
s.add(int(num))
num=input("Enter the 6th  number : ")
s.add(int(num))
num=input("Enter the 7th  number : ")
s.add(int(num))
num=input("Enter the 8th  number : ")
s.add(int(num))
print(s)


num=[]
n1=(int(input("Enter the number 1: ")))
num.append(n1)
n2=(int(input("Enter the number 2: ")))
num.append(n2)
n3=(int(input("Enter the number 3: ")))
num.append(n3)
n4=(int(input("Enter the number 4: ")))
num.append(n4)
n5=(int(input("Enter the number 5: ")))
num.append(n5)
n6=(int(input("Enter the number 6: ")))
num.append(n6)
n7=(int(input("Enter the number 7: ")))
num.append(n7)
n8=(int(input("Enter the number 8: ")))
num.append(n8)
print(num)